<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.29.3" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Markdig" Version="1.3.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="DevCoreBlog.Core\DevCoreBlog.Core.csproj" />
    <ProjectReference Include="DevCoreBlog.Data\DevCoreBlog.Data.csproj" />
    <ProjectReference Include="DevCoreBlog.Services\DevCoreBlog.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DevCoreBlog.Core\**" />
    <Content Remove="DevCoreBlog.Core\**" />
    <EmbeddedResource Remove="DevCoreBlog.Core\**" />
    <None Remove="DevCoreBlog.Core\**" />

    <Compile Remove="DevCoreBlog.Data\**" />
    <Content Remove="DevCoreBlog.Data\**" />
    <EmbeddedResource Remove="DevCoreBlog.Data\**" />
    <None Remove="DevCoreBlog.Data\**" />

    <Compile Remove="DevCoreBlog.Services\**" />
    <Content Remove="DevCoreBlog.Services\**" />
    <EmbeddedResource Remove="DevCoreBlog.Services\**" />
    <None Remove="DevCoreBlog.Services\**" />
  </ItemGroup>

</Project>
