// <auto-generated />
using System;
using DevCoreBlog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevCoreBlog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261010122743_ContentDocuments")]
    partial class ContentDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevCoreBlog.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EditVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DevCoreBlog.Core.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessScope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentJson")
                        .HasColumnType("text");

                    b.Property<string>("DocumentPlainText")
                        .HasColumnType("text");

                    b.Property<int?>("DocumentReadingMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("DocumentVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("DocumentWordCount")
                        .HasColumnType("integer");

                    b.Property<long>("EditVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailAlt")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("ThumbnailHeight")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailPublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ThumbnailWidth")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("CreatedDate", "Id")
                        .IsDescending(true, false);

                    b.HasIndex("PublishDate", "Id")
                        .IsDescending(true, false)
                        .HasFilter("\"IsActive\" AND \"IsPublished\"");

                    b.ToTable("Posts", t =>
                        {
                            t.HasCheckConstraint("CK_Posts_AccessScope", "\"AccessScope\" IN (0, 1)");

                            t.HasCheckConstraint("CK_Posts_ContentKind", "\"ContentKind\" IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_Posts_DocumentFacts", "(\"DocumentVersion\" IS NULL AND \"DocumentJson\" IS NULL AND \"DocumentPlainText\" IS NULL\n    AND \"DocumentWordCount\" IS NULL AND \"DocumentReadingMinutes\" IS NULL)\nOR\n(\"DocumentVersion\" IS NOT NULL AND \"DocumentJson\" IS NOT NULL AND \"DocumentPlainText\" IS NOT NULL\n    AND \"DocumentWordCount\" IS NOT NULL AND \"DocumentReadingMinutes\" IS NOT NULL\n    AND \"DocumentVersion\" = 1 AND octet_length(\"DocumentJson\") BETWEEN 1 AND 1048576\n    AND octet_length(\"DocumentPlainText\") <= 1048576\n    AND \"DocumentWordCount\" BETWEEN 0 AND 200000\n    AND \"DocumentReadingMinutes\" = (\"DocumentWordCount\" + 199) / 200)");

                            t.HasCheckConstraint("CK_Posts_NewsletterAccess", "\"ContentKind\" <> 4 OR \"AccessScope\" = 1");
                        });
                });

            modelBuilder.Entity("DevCoreBlog.Core.Entities.WebhookReceipt", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .UseCollation("C");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedPostId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Key");

                    b.HasIndex("PostId");

                    b.ToTable("WebhookReceipts");
                });

            modelBuilder.Entity("DevCoreBlog.Core.Entities.Post", b =>
                {
                    b.HasOne("DevCoreBlog.Core.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DevCoreBlog.Core.Entities.WebhookReceipt", b =>
                {
                    b.HasOne("DevCoreBlog.Core.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DevCoreBlog.Core.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
