// =============================================================================
// AdminCategoryController.cs — Admin Category CRUD Controller
// =============================================================================
// This controller provides full CRUD (Create, Read, Update, Delete) operations
// for blog categories in the admin panel.
//
// Architecture: This controller uses ICategoryService for business logic,
// not ApplicationDbContext directly.
// This follows the N-Tier architecture pattern:
//   Controller → Service → Repository → Database
//
// Key design decisions:
//   - Slug is auto-generated by CategoryService (not in Controller)
//   - Categories with associated posts cannot be deleted (cascade protection)
//   - ModelState.Remove("Slug") prevents validation errors on the auto-generated field
// =============================================================================

// Import the Service interface for business logic
using DevCoreBlog.Services.Interfaces;
// Import the Category entity
using DevCoreBlog.Core.Entities;
// Import MVC attributes and base classes
using Microsoft.AspNetCore.Mvc;
// Import the Authorize attribute to restrict access to authenticated users only
using Microsoft.AspNetCore.Authorization;

namespace DevCoreBlog.Controllers;

// [Authorize] attribute ensures only logged-in users can access any action in this controller.
// Unauthenticated users will be redirected to the login page (configured in Program.cs).
[Authorize]
// Inherit from Controller to access View(), RedirectToAction(), TempData, etc.
public class AdminCategoryController : Controller
{
    // Service field — injected via constructor (dependency injection)
    private readonly ICategoryService _categoryService;

    // Constructor receives service from the DI container.
    // ASP.NET Core creates a new scope per request, so this service is request-scoped.
    public AdminCategoryController(ICategoryService categoryService)
    {
        _categoryService = categoryService;
    }

    // -------------------------------------------------------------------------
    // INDEX — List all categories
    // -------------------------------------------------------------------------
    // GET: /AdminCategory
    // Fetches all categories from the service layer along with their related posts
    // so the view can display the post count per category.
    public async Task<IActionResult> Index()
    {
        // Delegate to service layer — business logic is in CategoryService
        var categories = await _categoryService.GetAllCategoriesWithPostsAsync();
        // Pass the list to the Index.cshtml view (which expects @model List<Category>)
        return View(categories);
    }

    // -------------------------------------------------------------------------
    // CREATE — Show the "New Category" form
    // -------------------------------------------------------------------------
    // GET: /AdminCategory/Create
    // Returns an empty form for creating a new category.
    public IActionResult Create()
    {
        return View();
    }

    // -------------------------------------------------------------------------
    // CREATE — Process the "New Category" form submission
    // -------------------------------------------------------------------------
    // POST: /AdminCategory/Create
    // Receives the form data bound to a Category object.
    // Delegates to service layer for slug generation and saving.
    [HttpPost]          // Only respond to POST requests (form submissions)
    [ValidateAntiForgeryToken]  // Protect against CSRF attacks using the hidden token in the form
    public async Task<IActionResult> Create([Bind("Name,Description")] Category category)
    {
        // Remove "Slug" from validation because it's auto-generated by CategoryService.
        // Without this, ModelState would fail since Slug is a non-nullable string.
        ModelState.Remove("Slug");

        // Check if all model validations passed (e.g. Name is not empty)
        if (ModelState.IsValid)
        {
            // Delegate to service layer — business logic (slug generation)
            // is handled in CategoryService.CreateCategoryAsync()
            await _categoryService.CreateCategoryAsync(category);
            // Redirect to the category list page after successful creation
            return RedirectToAction(nameof(Index));
        }

        // If validation failed, re-show the form with the user's input and error messages
        return View(category);
    }

    // -------------------------------------------------------------------------
    // EDIT — Show the "Edit Category" form (pre-filled)
    // -------------------------------------------------------------------------
    // GET: /AdminCategory/Edit/5
    // Finds the category by its Id and passes it to the Edit view.
    // If not found, returns a 404 Not Found response.
    public async Task<IActionResult> Edit(int id)
    {
        // Get category from service layer
        var category = await _categoryService.GetCategoryByIdAsync(id);
        // If no category exists with this Id, return 404
        if (category == null)
            return NotFound();

        // Pass the found category to the Edit.cshtml view for pre-filling the form
        return View(category);
    }

    // -------------------------------------------------------------------------
    // EDIT — Process the "Edit Category" form submission
    // -------------------------------------------------------------------------
    // POST: /AdminCategory/Edit/5
    // Updates an existing category. The Id in the URL must match the Id in the form.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Category category)
    {
        // Safety check: ensure the URL Id matches the form's hidden Id field
        if (id != category.Id)
            return NotFound();

        // Remove auto-generated fields from validation (same reason as Create)
        ModelState.Remove("Slug");

        if (ModelState.IsValid)
        {
            // Delegate to service layer — business logic (slug regeneration)
            // is handled in CategoryService.UpdateCategoryAsync()
            await _categoryService.UpdateCategoryAsync(category);
            return RedirectToAction(nameof(Index));
        }

        // If validation failed, re-show the form with errors
        return View(category);
    }

    // -------------------------------------------------------------------------
    // DELETE — Remove a category (with protection)
    // -------------------------------------------------------------------------
    // POST: /AdminCategory/Delete/5
    // Deletes a category only if it has no associated posts.
    // If posts exist, deletion is blocked to prevent cascade data loss.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        // Delegate to service layer — business logic (cascade protection)
        // is handled in CategoryService.DeleteCategoryAsync()
        var success = await _categoryService.DeleteCategoryAsync(id);

        // If deletion was blocked (category has posts), show error message
        if (!success)
        {
            // Store error message in TempData (survives one redirect)
            TempData["Error"] = "Bu kategoriye ait yazılar var, önce onları silin/taşıyın.";
        }

        return RedirectToAction(nameof(Index));
    }
}
