// =============================================================================
// AdminPostController.cs — Admin Blog Post CRUD Controller
// =============================================================================
// This controller provides full CRUD (Create, Read, Update, Delete) operations
// for blog posts in the admin panel.
//
// Architecture: This controller uses IPostService and ICategoryService
// for business logic, not ApplicationDbContext directly.
// This follows the N-Tier architecture pattern:
//   Controller → Service → Repository → Database
//
// Key design decisions:
//   - Slug is auto-generated by PostService (not in Controller)
//   - CreatedDate is set by PostService (not in Controller)
//   - Category dropdown is populated via ICategoryService
//   - ModelState.Remove("Slug") and ModelState.Remove("Category") prevent
//     validation errors on auto-generated and navigation properties
// =============================================================================

// Import the Service interfaces for business logic
using DevCoreBlog.Services.Interfaces;
using DevCoreBlog.Services.Images;
// Import the Post entity
using DevCoreBlog.Core.Entities;
// Import MVC attributes and base classes
using Microsoft.AspNetCore.Mvc;
// Import SelectList for populating the category dropdown in views
using Microsoft.AspNetCore.Mvc.Rendering;
// Import the Authorize attribute to restrict access to authenticated users only
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace DevCoreBlog.Controllers;

// [Authorize] attribute ensures only logged-in users can access any action in this controller.
// Unauthenticated users will be redirected to the login page (configured in Program.cs).
[Authorize]

// Inherit from Controller to access View(), RedirectToAction(), ViewBag, etc.
public class AdminPostController : Controller
{
    // Service fields — injected via constructor (dependency injection)
    private readonly IPostService _postService;
    private readonly ICategoryService _categoryService;
    private readonly IImageService _imageService;

    // Constructor receives services from the DI container
    public AdminPostController(
        IPostService postService,
        ICategoryService categoryService,
        IImageService imageService)
    {
        _postService = postService;
        _categoryService = categoryService;
        _imageService = imageService;
    }

    // -------------------------------------------------------------------------
    // INDEX — List all posts
    // -------------------------------------------------------------------------
    // GET: /AdminPost
    // Fetches all posts ordered by creation date (newest first),
    // including their related Category for display in the table.
    public async Task<IActionResult> Index()
    {
        // Fetch all categories for the client-side filter dropdown
        ViewBag.Categories = await _categoryService.GetAllCategoriesAsync();

        // Delegate to service layer — business logic is in PostService
        var posts = await _postService.GetAllPostsAsync();
        return View(posts);
    }

    // -------------------------------------------------------------------------
    // TOGGLE PUBLISH — Instant inline status toggle without page reload
    // -------------------------------------------------------------------------
    // POST: /AdminPost/TogglePublish/5
    // Toggles the IsPublished boolean flag on the post and returns JSON.
    [HttpPost]
    public async Task<IActionResult> TogglePublish(int id)
    {
        var post = await _postService.GetPostByIdAsync(id);
        if (post == null)
        {
            return NotFound(new { success = false, message = "Post not found." });
        }

        // Toggle publication state
        post.IsPublished = !post.IsPublished;
        await _postService.UpdatePostAsync(post);

        return Json(new
        {
            success = true,
            isPublished = post.IsPublished,
            message = post.IsPublished ? $"'{post.Title}' is now Published." : $"'{post.Title}' moved to Drafts."
        });
    }


    // -------------------------------------------------------------------------
    // CREATE — Show the "New Post" form
    // -------------------------------------------------------------------------
    // GET: /AdminPost/Create
    // Populates the category dropdown via ViewBag and returns the empty form.
    public async Task<IActionResult> Create()
    {
        // Get all categories from service layer for the dropdown
        await PopulateCategorySelectAsync();
        
        // Pass a new Post with PublishDate as Local time so the form defaults correctly
        var post = new Post { PublishDate = DateTime.Now };
        return View(post);
    }

    // -------------------------------------------------------------------------
    // CREATE — Process the "New Post" form submission
    // -------------------------------------------------------------------------
    // POST: /AdminPost/Create
    // Receives form data bound to a Post object, delegates to service layer
    // for slug generation and date setting, then saves to the database.
    [HttpPost]
    [ValidateAntiForgeryToken]  // CSRF protection
    [RequestSizeLimit(ImageUploadPolicy.MaximumRequestBytes)]
    [RequestFormLimits(MultipartBodyLengthLimit = ImageUploadPolicy.MaximumRequestBytes)]
    public async Task<IActionResult> Create(
        [Bind("Title,Content,CategoryId,ThumbnailUrl,Summary,Excerpt,IsPublished,IsActive,PublishDate")] Post post,
        IFormFile? thumbnailFile,
        CancellationToken cancellationToken)
    {
        // Remove auto-generated and navigation fields from validation.
        // "Slug" is auto-generated by PostService — not user input.
        // "Category" is a navigation property — EF Core handles it, not the form.
        ModelState.Remove("Id");
        ModelState.Remove("Slug");
        ModelState.Remove("Category");
        ModelState.Remove("CreatedDate");
        ModelState.Remove("ViewCount");
        ModelState.Remove("ThumbnailUrl"); // we set this manually if a file is uploaded

        if (ModelState.IsValid && thumbnailFile is not null)
        {
            await TrySetThumbnailAsync(post, thumbnailFile, cancellationToken);
        }

        if (ModelState.IsValid)
        {
            // Delegate to service layer — business logic (slug generation, date setting)
            // is handled in PostService.CreatePostAsync()
            await _postService.CreatePostAsync(post);
            return RedirectToAction(nameof(Index));
        }

        // If validation failed, re-populate the dropdown and re-show the form
        await PopulateCategorySelectAsync(post.CategoryId);
        return View(post);
    }

    // -------------------------------------------------------------------------
    // EDIT — Show the "Edit Post" form (pre-filled)
    // -------------------------------------------------------------------------
    // GET: /AdminPost/Edit/5
    // Finds the post by Id and populates the category dropdown with the
    // current category pre-selected.
    public async Task<IActionResult> Edit(int id)
    {
        // Get post from service layer
        var post = await _postService.GetPostByIdAsync(id);
        if (post == null)
            return NotFound();

        // Convert UTC PublishDate to Local time so the user sees their own time in the edit form
        if (post.PublishDate.Kind == DateTimeKind.Utc)
        {
            post.PublishDate = post.PublishDate.ToLocalTime();
        }

        // Get all categories for the dropdown
        await PopulateCategorySelectAsync(post.CategoryId);
        return View(post);
    }

    // -------------------------------------------------------------------------
    // EDIT — Process the "Edit Post" form submission
    // -------------------------------------------------------------------------
    // POST: /AdminPost/Edit/5
    // Updates an existing post. The Id in the URL must match the form's hidden Id.
    [HttpPost]
    [ValidateAntiForgeryToken]
    [RequestSizeLimit(ImageUploadPolicy.MaximumRequestBytes)]
    [RequestFormLimits(MultipartBodyLengthLimit = ImageUploadPolicy.MaximumRequestBytes)]
    public async Task<IActionResult> Edit(
        int id,
        [Bind("Id,Title,Content,CategoryId,ThumbnailUrl,Summary,Excerpt,IsPublished,IsActive,PublishDate")] Post post,
        IFormFile? thumbnailFile,
        CancellationToken cancellationToken)
    {
        // Safety check: URL Id must match the form's hidden Id field
        if (id != post.Id)
            return NotFound();

        // Remove auto-generated and navigation fields from validation
        ModelState.Remove("Slug");
        ModelState.Remove("Category");
        ModelState.Remove("CreatedDate");
        ModelState.Remove("ViewCount");
        ModelState.Remove("ThumbnailUrl"); // we set this manually if a file is uploaded

        if (ModelState.IsValid && thumbnailFile is not null)
        {
            await TrySetThumbnailAsync(post, thumbnailFile, cancellationToken);
        }

        if (ModelState.IsValid)
        {
            // Delegate to service layer — business logic (slug regeneration)
            // is handled in PostService.UpdatePostAsync()
            await _postService.UpdatePostAsync(post);
            return RedirectToAction(nameof(Index));
        }

        // If validation failed, re-populate the dropdown and re-show the form
        await PopulateCategorySelectAsync(post.CategoryId);
        return View(post);
    }

    // -------------------------------------------------------------------------
    // DELETE — Remove a post
    // -------------------------------------------------------------------------
    // POST: /AdminPost/Delete/5
    // Deletes a post by Id. No protection needed here (unlike categories),
    // because deleting a post doesn't cascade-delete anything else.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        // Delegate to service layer — business logic is in PostService
        await _postService.DeletePostAsync(id);
        return RedirectToAction(nameof(Index));
    }

    // -------------------------------------------------------------------------
    // UPLOAD EDITOR IMAGE — Drag-and-drop & clipboard image/GIF upload to Cloudinary
    // -------------------------------------------------------------------------
    // POST: /AdminPost/UploadEditorImage
    // Uploads editor images asynchronously to Cloudinary and returns the hosted URL.
    [HttpPost]
    [RequestSizeLimit(ImageUploadPolicy.MaximumRequestBytes)]
    [RequestFormLimits(MultipartBodyLengthLimit = ImageUploadPolicy.MaximumRequestBytes)]
    public Task<IActionResult> UploadEditorImage(
        IFormFile? file,
        CancellationToken cancellationToken)
    {
        return UploadImageAsync(file, cancellationToken);
    }

    // -------------------------------------------------------------------------
    // UPLOAD — Fallback local image upload for legacy markdown compatibility
    // -------------------------------------------------------------------------
    // POST: /AdminPost/UploadImage
    [HttpPost]
    [RequestSizeLimit(ImageUploadPolicy.MaximumRequestBytes)]
    [RequestFormLimits(MultipartBodyLengthLimit = ImageUploadPolicy.MaximumRequestBytes)]
    public Task<IActionResult> UploadImage(
        IFormFile? file,
        CancellationToken cancellationToken)
    {
        return UploadImageAsync(file, cancellationToken);
    }

    private async Task<bool> TrySetThumbnailAsync(
        Post post,
        IFormFile thumbnailFile,
        CancellationToken cancellationToken)
    {
        var outcome = await _imageService.UploadImageAsync(
            thumbnailFile,
            cancellationToken);
        if (!outcome.Succeeded || outcome.Url is null)
        {
            ModelState.AddModelError("thumbnailFile", outcome.Message);
            return false;
        }

        post.ThumbnailUrl = outcome.Url;
        return true;
    }

    private async Task<IActionResult> UploadImageAsync(
        IFormFile? file,
        CancellationToken cancellationToken)
    {
        var outcome = await _imageService.UploadImageAsync(file, cancellationToken);
        var payload = new
        {
            success = outcome.Succeeded,
            url = outcome.Url,
            message = outcome.Message
        };

        if (outcome.Succeeded)
        {
            return Ok(payload);
        }

        return outcome.FailureKind switch
        {
            ImageUploadFailureKind.FileTooLarge =>
                StatusCode(StatusCodes.Status413PayloadTooLarge, payload),
            ImageUploadFailureKind.StorageUnavailable =>
                StatusCode(StatusCodes.Status503ServiceUnavailable, payload),
            _ => BadRequest(payload)
        };
    }

    private async Task PopulateCategorySelectAsync(int? selectedCategoryId = null)
    {
        var categories = await _categoryService.GetAllCategoriesAsync();
        ViewBag.CategoryId = new SelectList(
            categories,
            "Id",
            "Name",
            selectedCategoryId);
    }
}
