// =============================================================================
// AdminPostController.cs — Admin Blog Post CRUD Controller
// =============================================================================
// This controller provides full CRUD (Create, Read, Update, Delete) operations
// for blog posts in the admin panel.
//
// Architecture: This controller uses IPostService and ICategoryService
// for business logic, not ApplicationDbContext directly.
// This follows the N-Tier architecture pattern:
//   Controller → Service → Repository → Database
//
// Key design decisions:
//   - Slug is auto-generated by PostService (not in Controller)
//   - CreatedDate is set by PostService (not in Controller)
//   - Category dropdown is populated via ICategoryService
//   - ModelState.Remove("Slug") and ModelState.Remove("Category") prevent
//     validation errors on auto-generated and navigation properties
// =============================================================================

// Import the Service interfaces for business logic
using DevCoreBlog.Services.Interfaces;
using DevCoreBlog.Services.Images;
using DevCoreBlog.Services.Publishing;
// Import the Post entity
using DevCoreBlog.Core.Entities;
using DevCoreBlog.Core.Publishing;
// Import MVC attributes and base classes
using Microsoft.AspNetCore.Mvc;
// Import SelectList for populating the category dropdown in views
using Microsoft.AspNetCore.Mvc.Rendering;
// Import the Authorize attribute to restrict access to authenticated users only
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using DevCoreBlog.Extensions;
using DevCoreBlog.Models.Admin;

namespace DevCoreBlog.Controllers;

// [Authorize] attribute ensures only logged-in users can access any action in this controller.
// Unauthenticated users will be redirected to the login page (configured in Program.cs).
[Authorize]

// Inherit from Controller to access View(), RedirectToAction(), ViewBag, etc.
public class AdminPostController : Controller
{
    // Service fields — injected via constructor (dependency injection)
    private readonly IPostService _postService;
    private readonly ICategoryService _categoryService;
    private readonly IImageService _imageService;
    private readonly PublicationTimeZone _publicationTimeZone;
    private readonly TimeProvider _timeProvider;
    private const int MaximumPreviewRequestBytes = 1_048_576;

    /// <summary>Exercises the local editor without binding input, reading posts or saving data.</summary>
    [HttpGet]
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public IActionResult EditorTrial()
    {
        Response.Headers["X-Robots-Tag"] = "noindex, nofollow, noarchive";
        return View();
    }

    // Constructor receives services from the DI container
    public AdminPostController(
        IPostService postService,
        ICategoryService categoryService,
        IImageService imageService,
        PublicationTimeZone publicationTimeZone,
        TimeProvider timeProvider)
    {
        _postService = postService;
        _categoryService = categoryService;
        _imageService = imageService;
        _publicationTimeZone = publicationTimeZone;
        _timeProvider = timeProvider;
    }

    // Filter and paginate in persistence; clamp stale pages after edits without losing context.
    [HttpGet]
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    public async Task<IActionResult> Index([FromQuery] AdminPostListInput input, CancellationToken cancellationToken)
    {
        if (!ModelState.IsValid) return BadRequest("Invalid inventory filters. Use page 1–1000 and size 10, 25, or 50.");
        var result = await _postService.GetAdminPostsPagedAsync(input.ToQuery(), cancellationToken);
        var categories = (await _categoryService.GetAllCategoriesAsync()).ToList();
        if (input.CategoryId is { } id && !categories.Any(category => category.Id == id)) return NotFound();
        var model = new AdminPostIndexModel(result, input, categories);
        if (input.Page > model.TotalPages) return RedirectToAction(nameof(Index), input.RouteValues(model.TotalPages));
        return View(model);
    }

    // -------------------------------------------------------------------------
    // TOGGLE PUBLISH — Instant inline status toggle without page reload
    // -------------------------------------------------------------------------
    // POST: /AdminPost/TogglePublish/5
    // Toggles the IsPublished boolean flag on the post and returns JSON.
    [HttpPost]
    public async Task<IActionResult> TogglePublish(int id, string? returnUrl = null)
    {
        if (!IsSafeListReturnUrl(returnUrl)) return BadRequest("Invalid return URL.");
        var post = await _postService.GetPostByIdAsync(id);
        if (post == null)
        {
            return NotFound(new { success = false, message = "Post not found." });
        }

        // Toggle publication state
        post.IsPublished = !post.IsPublished;
        var updateResult = await _postService.UpdatePostAsync(
            post,
            HttpContext.RequestAborted);
        if (!updateResult.IsValid)
        {
            return BadRequest(new
            {
                success = false,
                message = "The post no longer satisfies the content rules.",
                errors = updateResult.Errors
            });
        }

        if (returnUrl is not null) return LocalRedirect(returnUrl);

        return Json(new
        {
            success = true,
            isPublished = post.IsPublished,
            message = post.IsPublished
                ? "Publication enabled. The saved date and active category still control visibility."
                : "Post moved to Drafts."
        });
    }


    // -------------------------------------------------------------------------
    // CREATE — Show the "New Post" form
    // -------------------------------------------------------------------------
    // GET: /AdminPost/Create
    // Populates the category dropdown via ViewBag and returns the empty form.
    public async Task<IActionResult> Create()
    {
        // Get all categories from service layer for the dropdown
        await PopulateCategorySelectAsync();
        
        return View(new PostFormInput
        {
            PublishDate = _publicationTimeZone.ToSiteTime(
                _timeProvider.GetUtcNow().UtcDateTime),
            SiteTimeZoneId = _publicationTimeZone.Id
        });
    }

    /// <summary>Validates unsaved editor input and returns private HTML without write-side effects.</summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    [RequestSizeLimit(MaximumPreviewRequestBytes)]
    [RequestFormLimits(ValueLengthLimit = 800_000, MultipartBodyLengthLimit = MaximumPreviewRequestBytes)]
    public async Task<IActionResult> Preview(
        [Bind("Id,Title,Content,CategoryId,Summary,Excerpt,ThumbnailAlt,PublishDate")] PostFormInput? input,
        CancellationToken cancellationToken)
    {
        Response.Headers["X-Robots-Tag"] = "noindex, nofollow, noarchive";
        // Failed body binding may provide no model; reject it before accessing fields.
        if (Request.ContentLength > MaximumPreviewRequestBytes)
            return StatusCode(StatusCodes.Status413PayloadTooLarge, "Request too large.");
        if (input is null) return BadRequest("Invalid preview input.");
        // Stored media is read only; selected files and client cover URLs are never uploaded or trusted.
        var storedPost = input.Id > 0 ? await _postService.GetPostByIdAsync(input.Id) : null;
        if (input.Id < 0 || (input.Id > 0 && storedPost is null)) return NotFound();

        var post = MapToPost(input, storedPost);
        if (ModelState.IsValid)
            ModelState.AddContentErrors(await _postService.ValidatePostAsync(post, cancellationToken));

        var category = ModelState.IsValid
            ? await _categoryService.GetCategoryByIdAsync(input.CategoryId) : null;
        if (ModelState.IsValid && (category is null || !category.IsActive))
            ModelState.AddModelError(nameof(input.CategoryId), "Select an active category.");

        if (!ModelState.IsValid) Response.StatusCode = StatusCodes.Status400BadRequest;
        return View(new PostPreviewModel(post.Title, post.Content, category?.Name ?? string.Empty,
            post.ThumbnailUrl, post.ThumbnailAlt));
    }

    // -------------------------------------------------------------------------
    // CREATE — Process the "New Post" form submission
    // -------------------------------------------------------------------------
    // POST: /AdminPost/Create
    // Receives form data bound to a Post object, delegates to service layer
    // for slug generation and date setting, then saves to the database.
    [HttpPost]
    [ValidateAntiForgeryToken]  // CSRF protection
    [RequestSizeLimit(ImageUploadPolicy.MaximumRequestBytes)]
    [RequestFormLimits(MultipartBodyLengthLimit = ImageUploadPolicy.MaximumRequestBytes)]
    public async Task<IActionResult> Create(
        [Bind("Title,Content,CategoryId,Summary,Excerpt,ThumbnailAlt,SaveAction,IsActive,PublishDate")] PostFormInput input,
        IFormFile? thumbnailFile,
        Guid? recoveryRevision,
        CancellationToken cancellationToken)
    {
        var post = MapToPost(input, null);

        if (ModelState.IsValid)
        {
            var validationResult = await _postService.PrepareEditorSaveAsync(
                post, input.SaveAction, cancellationToken);
            ModelState.AddContentErrors(validationResult);
        }

        if (ModelState.IsValid && thumbnailFile is not null)
        {
            await TrySetThumbnailAsync(post, thumbnailFile, cancellationToken);
        }

        if (ModelState.IsValid)
        {
            // Delegate to service layer — business logic (slug generation, date setting)
            // is handled in PostService.CreatePostAsync()
            var createResult = await _postService.CreatePostAsync(
                post, cancellationToken, input.SaveAction);
            ModelState.AddContentErrors(createResult);
            if (createResult.IsValid)
            {
                return RedirectAfterSave("devcore_editor_draft_create", recoveryRevision);
            }
        }

        // If validation failed, re-populate the dropdown and re-show the form
        input.SiteTimeZoneId = _publicationTimeZone.Id;
        var categoryIsActive = await PopulateCategorySelectAsync(input.CategoryId);
        input.PublicationState = PostPublication.StateAt(post, categoryIsActive,
            _timeProvider.GetUtcNow().UtcDateTime);
        return View(input);
    }

    // -------------------------------------------------------------------------
    // EDIT — Show the "Edit Post" form (pre-filled)
    // -------------------------------------------------------------------------
    // GET: /AdminPost/Edit/5
    // Finds the post by Id and populates the category dropdown with the
    // current category pre-selected.
    public async Task<IActionResult> Edit(int id, string? returnUrl = null)
    {
        if (!IsSafeListReturnUrl(returnUrl)) return BadRequest("Invalid return URL.");
        // Get post from service layer
        var post = await _postService.GetPostByIdAsync(id);
        if (post == null)
            return NotFound();

        if (post.DocumentVersion is not null)
            return RedirectToAction("Edit", "AdminWriting", new { id, returnUrl });

        // Get all categories for the dropdown
        var categoryIsActive = await PopulateCategorySelectAsync(post.CategoryId);
        var input = MapToInput(post);
        input.ReturnUrl = returnUrl;
        input.PublicationState = PostPublication.StateAt(post, categoryIsActive,
            _timeProvider.GetUtcNow().UtcDateTime);
        return View(input);
    }

    // -------------------------------------------------------------------------
    // EDIT — Process the "Edit Post" form submission
    // -------------------------------------------------------------------------
    // POST: /AdminPost/Edit/5
    // Updates an existing post. The Id in the URL must match the form's hidden Id.
    [HttpPost]
    [ValidateAntiForgeryToken]
    [RequestSizeLimit(ImageUploadPolicy.MaximumRequestBytes)]
    [RequestFormLimits(MultipartBodyLengthLimit = ImageUploadPolicy.MaximumRequestBytes)]
    public async Task<IActionResult> Edit(
        int id,
        [Bind("Id,EditVersion,Title,Content,CategoryId,Summary,Excerpt,ThumbnailAlt,SaveAction,IsActive,PublishDate")] PostFormInput input,
        IFormFile? thumbnailFile,
        Guid? recoveryRevision,
        CancellationToken cancellationToken,
        string? returnUrl = null)
    {
        if (!IsSafeListReturnUrl(returnUrl)) return BadRequest("Invalid return URL.");
        input.ReturnUrl = returnUrl;
        // Safety check: URL Id must match the form's hidden Id field
        if (id != input.Id)
            return NotFound();

        // The stored cover is server-owned state. Preserve it unless a valid
        // replacement upload succeeds; never trust a client-posted URL.
        var existingPost = await _postService.GetPostByIdAsync(id);
        if (existingPost is null)
            return NotFound();

        if (input.EditVersion <= 0)
        {
            ModelState.AddModelError(string.Empty, "Reload this post before saving.");
        }
        else if (input.EditVersion != existingPost.EditVersion)
        {
            ModelState.AddModelError(string.Empty,
                "This post changed since you opened it. Your edits are still here. Reload the current post before trying again.");
            Response.StatusCode = StatusCodes.Status409Conflict;
        }

        // The tracked entity may change before a late DB conflict; retain the committed cover URL.
        var persistedThumbnailUrl = existingPost.ThumbnailUrl;
        var post = MapToPost(input, existingPost);
        // The browser edits seconds; retain the stored subsecond instant when
        // the displayed date was left unchanged.
        var displayedDate = _publicationTimeZone.ToSiteTime(existingPost.PublishDate);
        var displayedSecond = new DateTime(
            displayedDate.Ticks - displayedDate.Ticks % TimeSpan.TicksPerSecond,
            DateTimeKind.Unspecified);
        if (input.PublishDate == displayedSecond)
        {
            post.PublishDate = existingPost.PublishDate;
        }

        input.Slug = existingPost.Slug;
        input.ThumbnailUrl = existingPost.ThumbnailUrl;

        if (ModelState.IsValid)
        {
            var validationResult = await _postService.PrepareEditorSaveAsync(
                post, input.SaveAction, cancellationToken);
            ModelState.AddContentErrors(validationResult);
            if (validationResult.IsConflict) Response.StatusCode = StatusCodes.Status409Conflict;
        }

        if (ModelState.IsValid && thumbnailFile is not null)
        {
            await TrySetThumbnailAsync(post, thumbnailFile, cancellationToken);
        }

        if (ModelState.IsValid)
        {
            // The service preserves the stored slug when editable fields change.
            var updateResult = await _postService.UpdatePostAsync(
                post,
                cancellationToken,
                input.EditVersion, input.SaveAction);
            ModelState.AddContentErrors(updateResult);
            if (updateResult.IsConflict)
            {
                Response.StatusCode = StatusCodes.Status409Conflict;
            }
            if (updateResult.IsValid)
            {
                return RedirectAfterSave($"devcore_editor_draft_edit_{id}", recoveryRevision, returnUrl);
            }
        }

        // If validation failed, re-populate the dropdown and re-show the form
        input.ThumbnailUrl = persistedThumbnailUrl;
        input.SiteTimeZoneId = _publicationTimeZone.Id;
        var categoryIsActive = await PopulateCategorySelectAsync(input.CategoryId, existingPost.CategoryId);
        input.PublicationState = PostPublication.StateAt(existingPost, categoryIsActive,
            _timeProvider.GetUtcNow().UtcDateTime);
        input.IsPublished = existingPost.IsPublished;
        return View(input);
    }

    // -------------------------------------------------------------------------
    // DELETE — Remove a post
    // -------------------------------------------------------------------------
    // POST: /AdminPost/Delete/5
    // Deletes a post by Id. No protection needed here (unlike categories),
    // because deleting a post doesn't cascade-delete anything else.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        // Delegate to service layer — business logic is in PostService
        await _postService.DeletePostAsync(id);
        return RedirectToAction(nameof(Index));
    }

    // -------------------------------------------------------------------------
    // UPLOAD EDITOR IMAGE — Drag-and-drop & clipboard image/GIF upload to Cloudinary
    // -------------------------------------------------------------------------
    // POST: /AdminPost/UploadEditorImage
    // Uploads editor images asynchronously to Cloudinary and returns the hosted URL.
    [HttpPost]
    [RequestSizeLimit(ImageUploadPolicy.MaximumRequestBytes)]
    [RequestFormLimits(MultipartBodyLengthLimit = ImageUploadPolicy.MaximumRequestBytes)]
    public Task<IActionResult> UploadEditorImage(
        IFormFile? file,
        CancellationToken cancellationToken)
    {
        return UploadImageAsync(file, cancellationToken);
    }

    // -------------------------------------------------------------------------
    // UPLOAD — Fallback local image upload for legacy markdown compatibility
    // -------------------------------------------------------------------------
    // POST: /AdminPost/UploadImage
    [HttpPost]
    [RequestSizeLimit(ImageUploadPolicy.MaximumRequestBytes)]
    [RequestFormLimits(MultipartBodyLengthLimit = ImageUploadPolicy.MaximumRequestBytes)]
    public Task<IActionResult> UploadImage(
        IFormFile? file,
        CancellationToken cancellationToken)
    {
        return UploadImageAsync(file, cancellationToken);
    }

    // Emit a protected, one-use receipt only after persistence reports success.
    // The browser compares the exact local revision before clearing recovery text.
    private IActionResult RedirectAfterSave(string recoveryKey, Guid? revision, string? returnUrl = null)
    {
        if (revision is { } savedRevision && savedRevision != Guid.Empty)
        {
            TempData["SavedPostRecoveryKey"] = recoveryKey;
            TempData["SavedPostRecoveryRevision"] = savedRevision.ToString("D");
        }
        if (returnUrl is not null) return LocalRedirect(returnUrl);
        return RedirectToAction(nameof(Index));
    }

    // Only a bounded local inventory URL may influence navigation; reject before side effects.
    private bool IsSafeListReturnUrl(string? returnUrl)
    {
        if (returnUrl is null) return true;
        if (returnUrl.Length > 2048 || !Url.IsLocalUrl(returnUrl) || returnUrl.Any(char.IsControl)) return false;
        var path = returnUrl.Split('?')[0];
        return path.Equals("/AdminPost", StringComparison.OrdinalIgnoreCase) ||
            path.Equals("/AdminPost/", StringComparison.OrdinalIgnoreCase);
    }

    private async Task<bool> TrySetThumbnailAsync(
        Post post,
        IFormFile thumbnailFile,
        CancellationToken cancellationToken)
    {
        var outcome = await _imageService.UploadImageAsync(
            thumbnailFile,
            cancellationToken);
        if (!outcome.Succeeded || outcome.Url is null)
        {
            ModelState.AddModelError("thumbnailFile", outcome.Message);
            return false;
        }

        post.ThumbnailUrl = outcome.Url;
        post.ThumbnailPublicId = outcome.PublicId;
        post.ThumbnailWidth = outcome.Width;
        post.ThumbnailHeight = outcome.Height;
        return true;
    }

    private async Task<IActionResult> UploadImageAsync(
        IFormFile? file,
        CancellationToken cancellationToken)
    {
        var outcome = await _imageService.UploadImageAsync(file, cancellationToken);
        var payload = new
        {
            success = outcome.Succeeded,
            url = outcome.Url,
            message = outcome.Message
        };

        if (outcome.Succeeded)
        {
            return Ok(payload);
        }

        return outcome.FailureKind switch
        {
            ImageUploadFailureKind.FileTooLarge =>
                StatusCode(StatusCodes.Status413PayloadTooLarge, payload),
            ImageUploadFailureKind.StorageUnavailable =>
                StatusCode(StatusCodes.Status503ServiceUnavailable, payload),
            _ => BadRequest(payload)
        };
    }

    private async Task<bool> PopulateCategorySelectAsync(
        int? selectedCategoryId = null, int? stateCategoryId = null)
    {
        var categories = (await _categoryService.GetAllCategoriesAsync()).ToList();
        ViewBag.CategoryId = new SelectList(
            categories.Where(category => category.IsActive),
            "Id",
            "Name",
            selectedCategoryId);
        return categories.Any(category => category.Id == (stateCategoryId ?? selectedCategoryId) && category.IsActive);
    }

    private static Post MapToPost(PostFormInput input, Post? storedPost)
    {
        return new Post
        {
            Id = input.Id,
            Title = input.Title,
            Content = input.Content,
            CategoryId = input.CategoryId,
            Summary = input.Summary ?? string.Empty,
            Excerpt = input.Excerpt ?? string.Empty,
            IsPublished = input.IsPublished,
            IsActive = input.IsActive,
            PublishDate = input.PublishDate,
            ContentKind = storedPost?.ContentKind ?? PostContentKind.Unclassified,
            AccessScope = storedPost?.AccessScope ?? PostAccessScope.Public,
            ThumbnailUrl = storedPost?.ThumbnailUrl ?? string.Empty,
            ThumbnailPublicId = storedPost?.ThumbnailPublicId,
            ThumbnailWidth = storedPost?.ThumbnailWidth,
            ThumbnailHeight = storedPost?.ThumbnailHeight,
            ThumbnailAlt = input.ThumbnailAlt
        };
    }

    private PostFormInput MapToInput(Post post)
    {
        return new PostFormInput
        {
            Id = post.Id,
            EditVersion = post.EditVersion,
            SaveAction = PostSaveAction.Save,
            Title = post.Title,
            Content = post.Content,
            CategoryId = post.CategoryId,
            Summary = post.Summary,
            Excerpt = post.Excerpt,
            IsPublished = post.IsPublished,
            IsActive = post.IsActive,
            PublishDate = _publicationTimeZone.ToSiteTime(post.PublishDate),
            SiteTimeZoneId = _publicationTimeZone.Id,
            Slug = post.Slug,
            ThumbnailUrl = post.ThumbnailUrl,
            ThumbnailAlt = post.ThumbnailAlt
        };
    }
}
