// =============================================================================
// Post.cs — Blog Post Entity Model
// =============================================================================
// This class represents a blog post in the database.
// Each post has a title, URL-friendly slug, summary, full content,
// a creation timestamp, a published flag, and belongs to one Category.
//
// EF Core uses this class to map to the "Posts" table in PostgreSQL.
// The migration "InitialCreate" has already been applied to the database.
//
// Inheritance: Post inherits from BaseEntity, which provides:
//   - Id (primary key)
//   - CreatedDate (timestamp)
//   - IsActive (soft-delete flag)
// =============================================================================

using DevCoreBlog.Core.Entities;

namespace DevCoreBlog.Core.Entities;

// This class maps to the "Posts" table in the database
// Inherits Id, CreatedDate, IsActive from BaseEntity
public class Post : BaseEntity
{
    // The title of the blog post (e.g. "ASP.NET Core ile Blog Yazma")
    public string Title { get; set; } = string.Empty;

    // URL-friendly version of the title (e.g. "asp-net-core-ile-blog-yazma")
    // Auto-generated by SlugGenerator — never entered by the user
    public string Slug { get; set; } = string.Empty;

    // A short summary/excerpt shown on the post listing page
    public string Summary { get; set; } = string.Empty;

    // The thumbnail URL for the post image
    public string ThumbnailUrl { get; set; } = string.Empty;

    // Server-owned upload metadata; legacy URL-only covers remain nullable.
    public string? ThumbnailPublicId { get; set; }
    public int? ThumbnailWidth { get; set; }
    public int? ThumbnailHeight { get; set; }

    // Empty means decorative; never derive a description from the title.
    public string? ThumbnailAlt { get; set; }

    // A short excerpt for the post (can be used instead of Summary if needed)
    public string Excerpt { get; set; } = string.Empty;

    // Is the post published or draft?
    public bool IsPublished { get; set; } = false;

    // Server-owned classification; legacy form saves preserve the stored values.
    public PostContentKind ContentKind { get; set; } = PostContentKind.Unclassified;
    public PostAccessScope AccessScope { get; set; } = PostAccessScope.Public;


    // The full content of the blog post (plain text in <textarea>)
    public string Content { get; set; } = string.Empty;

    // An all-null set identifies legacy content. Only the document use case owns these fields.
    public int? DocumentVersion { get; set; }
    public string? DocumentJson { get; set; }
    public string? DocumentPlainText { get; set; }
    public int? DocumentWordCount { get; set; }
    public int? DocumentReadingMinutes { get; set; }

    // -----------------------------------------------------------------------
    // VIEW COUNT — Tracks how many times this post has been viewed
    // -----------------------------------------------------------------------
    // Counts eligible anonymous public detail GET requests, not unique people.
    // HEAD and authenticated admin requests do not count; bots may still count.
    // Default value is 0 and no visitor identity is stored.
    public int ViewCount { get; set; } = 0;

    // Content edits advance this token; visitor counter writes leave it unchanged.
    public long EditVersion { get; set; } = 1;

    // Last meaningful content edit in UTC; historical and newly created posts remain null.
    public DateTime? UpdatedDate { get; set; }

    // -----------------------------------------------------------------------
    // SCHEDULED PUBLISHING
    // -----------------------------------------------------------------------
    // The date and time when the post should become visible to visitors.
    // If this date is in the future, the post remains hidden on the public site.
    // Defaults to UTC Now (immediately published).
    public DateTime PublishDate { get; set; } = DateTime.UtcNow;

    // -----------------------------------------------------------------------
    // RELATIONSHIP: Foreign key and navigation property to Category
    // -----------------------------------------------------------------------
    // CategoryId is the foreign key — stores the Id of the parent Category.
    // EF Core convention: property named "<NavigationProperty>Id" is auto-detected as FK.
    public int CategoryId { get; set; }

    // Navigation property — EF Core fills this with the related Category entity
    // when you use .Include(p => p.Category) in a query.
    // "= null!" tells the nullable analyzer that EF Core will set this value.
    public Category Category { get; set; } = null!;
}
