// =============================================================================
// Post.cs — Blog Post Entity Model
// =============================================================================
// This class represents a blog post in the database.
// Each post has a title, URL-friendly slug, summary, full content,
// a creation timestamp, a published flag, and belongs to one Category.
//
// EF Core uses this class to map to the "Posts" table in PostgreSQL.
// The migration "InitialCreate" has already been applied to the database.
//
// Inheritance: Post inherits from BaseEntity, which provides:
//   - Id (primary key)
//   - CreatedDate (timestamp)
//   - IsActive (soft-delete flag)
// =============================================================================

using DevCoreBlog.Core.Entities;

namespace DevCoreBlog.Core.Entities;

// This class maps to the "Posts" table in the database
// Inherits Id, CreatedDate, IsActive from BaseEntity
public class Post : BaseEntity
{
    // The title of the blog post (e.g. "ASP.NET Core ile Blog Yazma")
    public string Title { get; set; } = string.Empty;

    // URL-friendly version of the title (e.g. "asp-net-core-ile-blog-yazma")
    // Auto-generated by SlugGenerator — never entered by the user
    public string Slug { get; set; } = string.Empty;

    // A short summary/excerpt shown on the post listing page
    public string Summary { get; set; } = string.Empty;

    // The full content of the blog post (plain text in <textarea>)
    public string Content { get; set; } = string.Empty;

    // -----------------------------------------------------------------------
    // VIEW COUNT — Tracks how many times this post has been viewed
    // -----------------------------------------------------------------------
    // Every time a visitor opens the Detail page, this counter increments by 1.
    // Default value is 0 (new posts start with zero views).
    // This is a simple analytics metric — no user tracking or cookies involved.
    public int ViewCount { get; set; } = 0;

    // -----------------------------------------------------------------------
    // SCHEDULED PUBLISHING
    // -----------------------------------------------------------------------
    // The date and time when the post should become visible to visitors.
    // If this date is in the future, the post remains hidden on the public site.
    // Defaults to UTC Now (immediately published).
    public DateTime PublishDate { get; set; } = DateTime.UtcNow;

    // -----------------------------------------------------------------------
    // RELATIONSHIP: Foreign key and navigation property to Category
    // -----------------------------------------------------------------------
    // CategoryId is the foreign key — stores the Id of the parent Category.
    // EF Core convention: property named "<NavigationProperty>Id" is auto-detected as FK.
    public int CategoryId { get; set; }

    // Navigation property — EF Core fills this with the related Category entity
    // when you use .Include(p => p.Category) in a query.
    // "= null!" tells the nullable analyzer that EF Core will set this value.
    public Category Category { get; set; } = null!;
}
