\set ON_ERROR_STOP on

-- This fixture must never run against a development or production database.
DO $$
BEGIN
    IF current_database() <> 'devcoreblog_f01_test' THEN
        RAISE EXCEPTION 'Refusing to load F01 fixture into database %', current_database();
    END IF;
END
$$;

DROP TABLE IF EXISTS "Posts";
DROP TABLE IF EXISTS "Categories";

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL
);

CREATE TABLE "Posts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" text NOT NULL,
    "Slug" text NOT NULL,
    "Summary" text NOT NULL,
    "Content" text NOT NULL,
    "CategoryId" integer NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "ViewCount" integer NOT NULL,
    "PublishDate" timestamp with time zone NOT NULL,
    "Excerpt" text NOT NULL,
    "IsPublished" boolean NOT NULL,
    "ThumbnailUrl" text NOT NULL,
    CONSTRAINT "FK_Posts_Categories_CategoryId"
        FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Posts_CategoryId" ON "Posts" ("CategoryId");

INSERT INTO "Categories" ("Id", "Name", "Slug", "CreatedDate", "IsActive") VALUES
    (1001, 'F01 Active Category', 'f01-active', CURRENT_TIMESTAMP - interval '60 days', true),
    (1002, 'F01 Inactive Category', 'f01-inactive', CURRENT_TIMESTAMP - interval '60 days', false);

INSERT INTO "Posts" (
    "Id", "Title", "Slug", "Summary", "Content", "CategoryId",
    "CreatedDate", "IsActive", "ViewCount", "PublishDate", "Excerpt",
    "IsPublished", "ThumbnailUrl"
) VALUES
    (2001, 'F03 <img src=x onerror="window.__f03ToastXss=true">', 'f01-visible', 'F01_VISIBLE_MARKER',
     'F01_VISIBLE_MARKER', 1001, CURRENT_TIMESTAMP - interval '10 days', true, 3,
     CURRENT_TIMESTAMP - interval '9 days', 'F01 visible excerpt', true, ''),
    (2002, 'F01 Future Post', 'f01-future-visible-marker', 'F01_FUTURE_VISIBLE_MARKER',
     'F01_FUTURE_VISIBLE_MARKER', 1001, CURRENT_TIMESTAMP, true, 0,
     CURRENT_TIMESTAMP + interval '30 days', 'F01 future excerpt', true, ''),
    (2003, 'F01 Draft Post', 'f01-draft', 'F01_DRAFT_MARKER',
     'F01_DRAFT_MARKER', 1001, CURRENT_TIMESTAMP, true, 0,
     CURRENT_TIMESTAMP - interval '1 day', 'F01 draft excerpt', false,
     'https://images.example.test/f11-existing-cover.png'),
    (2004, 'F01 Inactive Post', 'f01-inactive-post', 'F01_INACTIVE_MARKER',
     'F01_INACTIVE_MARKER', 1001, CURRENT_TIMESTAMP, false, 0,
     CURRENT_TIMESTAMP - interval '1 day', 'F01 inactive excerpt', true, ''),
    (2005, 'F01 Markdown XSS', 'f01-markdown-xss', 'F01_MARKDOWN_XSS_MARKER',
     $f04markdown$# F04_SAFE_HEADING

<script>window.__f01MarkdownXss=true</script>
<img src=x onerror="window.__f04ImageXss=true">
<svg onload="window.__f04SvgXss=true"></svg>

[Dangerous JavaScript](javascript:alert('f04'))
[Dangerous encoded JavaScript](java%73cript:alert('f04'))
[Dangerous entity JavaScript](jav&#x61;script:alert('f04'))
[Dangerous VBScript](vbscript:msgbox('f04'))
![Dangerous SVG image](data:image/svg+xml,%3Csvg%20onload%3Dalert%281%29%3E)

[Generic attribute probe](https://example.com/docs){onclick="window.__f04AttributeXss=true"}
[Safe HTTPS link](https://example.com/docs)
[Safe relative link](/post/f01-visible)

[video](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
[video](https://www.youtube.com.evil.example/watch?v=dQw4w9WgXcQ)

| Feature | Status |
| --- | --- |
| F04_TABLE_MARKER | safe |

- F04_LIST_MARKER

```csharp
Console.WriteLine("F04_CODE_MARKER");
```

F01_MARKDOWN_XSS_MARKER$f04markdown$,
     1001, CURRENT_TIMESTAMP, true, 0, CURRENT_TIMESTAMP - interval '1 day',
     'F01 markdown excerpt', true, ''),
    (2006, 'İstanbul, IĞDIR ve ğüşiöç', 'f01-turkce-karakterler', 'F01_TURKISH_MARKER',
     'Türkçe arama örneği: İstanbul, IĞDIR ve ğüşiöç.', 1001,
     CURRENT_TIMESTAMP, true, 0, CURRENT_TIMESTAMP - interval '1 day',
     'F01 Turkish excerpt', true, ''),
    (2007, 'F01 Long Draft', 'f01-long-draft', repeat('F01_LONG_MARKER ', 800),
     repeat('F01_LONG_CONTENT ', 4000), 1001, CURRENT_TIMESTAMP, true, 0,
     CURRENT_TIMESTAMP - interval '1 day', repeat('F01_LONG_EXCERPT ', 50), false, ''),
    (2008, 'F01 Visible Post', 'f01-duplicate-title', 'F01_DUPLICATE_TITLE_MARKER',
     'F01_DUPLICATE_TITLE_MARKER', 1002, CURRENT_TIMESTAMP, true, 0,
     CURRENT_TIMESTAMP - interval '1 day', 'F01 duplicate excerpt', true, '');

SELECT setval(pg_get_serial_sequence('"Categories"', 'Id'), 1002, true);
SELECT setval(pg_get_serial_sequence('"Posts"', 'Id'), 2008, true);
