// =============================================================================
// Category.cs — Blog Category Entity Model
// =============================================================================
// This class represents a blog category in the database.
// Each category has a name, URL-friendly slug, and a collection of posts.
//
// Relationship: One Category → Many Posts (one-to-many)
// EF Core uses this class to map to the "Categories" table in PostgreSQL.
// =============================================================================

namespace DevCoreBlog.Models;

// This class maps to the "Categories" table in the database
public class Category
{
    // Primary key — auto-incremented integer by EF Core convention
    public int Id { get; set; }

    // The display name of the category (e.g. "C# Dersleri")
    public string Name { get; set; } = string.Empty;

    // URL-friendly version of the name (e.g. "c-sharp-dersleri")
    // Auto-generated by SlugGenerator — never entered by the user
    public string Slug { get; set; } = string.Empty;

    // -----------------------------------------------------------------------
    // RELATIONSHIP: Collection navigation property to Posts
    // -----------------------------------------------------------------------
    // This collection holds all posts that belong to this category.
    // EF Core fills it when you use .Include(c => c.Posts) in a query.
    // Initialized to an empty list to prevent null reference exceptions.
    public ICollection<Post> Posts { get; set; } = new List<Post>();
}
