// =============================================================================
// ErrorViewModel.cs — Error Page View Model
// =============================================================================
// This model is used exclusively by the Error.cshtml view to display
// a request correlation ID for debugging purposes.
// It is generated by HomeController.Error() and contains no database mapping.
// =============================================================================

namespace DevCoreBlog.Models;

// View model for the error page — not a database entity
public class ErrorViewModel
{
    // A unique identifier for the current HTTP request.
    // Helps correlate user-reported errors with server-side logs.
    public string? RequestId { get; set; }

    // Computed property — returns true if RequestId has a value.
    // Used in the view to conditionally show the RequestId section.
    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}
