// =============================================================================
// Post.cs — Blog Post Entity Model
// =============================================================================
// This class represents a blog post in the database.
// Each post has a title, URL-friendly slug, summary, full content,
// a creation timestamp, a published flag, and belongs to one Category.
//
// EF Core uses this class to map to the "Posts" table in PostgreSQL.
// The migration "InitialCreate" has already been applied to the database.
// =============================================================================

namespace DevCoreBlog.Models;

// This class maps to the "Posts" table in the database
public class Post
{
    // Primary key — auto-incremented integer by EF Core convention
    public int Id { get; set; }

    // The title of the blog post (e.g. "ASP.NET Core ile Blog Yazma")
    public string Title { get; set; } = string.Empty;

    // URL-friendly version of the title (e.g. "asp-net-core-ile-blog-yazma")
    // Auto-generated by SlugGenerator — never entered by the user
    public string Slug { get; set; } = string.Empty;

    // A short summary/excerpt shown on the post listing page
    public string Summary { get; set; } = string.Empty;

    // The full content of the blog post (plain text in <textarea>)
    public string Content { get; set; } = string.Empty;

    // When the post was created — always set to DateTime.UtcNow in the controller
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Whether this post is visible to the public.
    // When false, the post only appears in the admin panel.
    public bool IsPublished { get; set; } = true;

    // -----------------------------------------------------------------------
    // RELATIONSHIP: Foreign key and navigation property to Category
    // -----------------------------------------------------------------------
    // CategoryId is the foreign key — stores the Id of the parent Category.
    // EF Core convention: property named "<NavigationProperty>Id" is auto-detected as FK.
    public int CategoryId { get; set; }

    // Navigation property — EF Core fills this with the related Category entity
    // when you use .Include(p => p.Category) in a query.
    // "= null!" tells the nullable analyzer that EF Core will set this value.
    public Category Category { get; set; } = null!;
}
